spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: config
      profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: haril
    password: haril

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
server:
  port: 8889