spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: config
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 8889